### ISSUE TITLE
Implement org.freedesktop.ScreenSaver support

### ISSUE THREAD

**Issue by rafaelrc7** [rafaelrc7/wayland-pipewire-idle-inhibit#2]
In some platforms, idle can be inhibited by D-Bus messages, as described in:

https://specifications.freedesktop.org/idle-inhibit-spec/latest/re01.html

Implementing support for this would wide the platform support of the program. And can be used in platforms where support for the wayland idle inhibit protocol is broken or not implemented such as in the case of https://github.com/rafaelrc7/wayland-pipewire-idle-inhibit/issues/1.

**Comment by tjkirch** [comment]
I've been looking at [zbus](https://lib.rs/crates/zbus) for this, which can generate DBus APIs easily and is all Rust.  There is a project, [caffeinate](https://github.com/al3xtjames/caffeinate), that [has done dbus-based inhibition](https://github.com/al3xtjames/caffeinate/blob/master/src/dbus_sleep_inhibitor.rs) using the [native dbus bindings](https://lib.rs/crates/dbus).  I'm not sure of your preferences in this area; it seems like you wouldn't mind the dbus bindings since the program already uses the pipewire bindings?

**Comment by rafaelrc7** [comment]
That's a good suggestion, thanks. I was looking into the `dbus` crate, but this `zbus` also looks interesting. I will look into both options. The first step in this is that I want to create a trait that represents "indle inhibitors", so that the code could work by swapping the wayland and dbus implementation and even a dryrun one that just logs. It should be simple, but I'm a bit busy with university, I believe I can work on this this weekend.

**Comment by tjkirch** [comment]
Awesome!  I'd also be happy to give it a try, if you're busy or would like help.

**Comment by rafaelrc7** [comment]
I started the implementation in the https://github.com/rafaelrc7/wayland-pipewire-idle-inhibit/tree/feat/dbus branch. I started by generalising the IdleInhibitor trait, and now I will try to implement the dbus version.

**Comment by tjkirch** [comment]
Nice!  I looked through and I had a quick thought regarding this bit:

https://github.com/rafaelrc7/wayland-pipewire-idle-inhibit/commit/de7e0fa759f50cbcc626c4a45dfbdb9b1722918e#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcR108-R110

I know the branch is in progress, so maybe you're way ahead of me, but I was curious.  I see that it's panicking if any of the inhibitors fail.  The third commit allows disabling a specific inhibitor.  Does this mean the user has to enable only the inhibitors that work on their system?  Would it make sense to only warn on failure, or perhaps to only panic if _all_ inhibitors fail?  Then the program would work without the user having to know in advance and select their inhibitors.  Or perhaps the program could check what's supported by the system?  Then it would be safer to panic.

**Comment by rafaelrc7** [comment]
Yeah, my plan was for letting the user set what idle inhibitor should be enabled. I believe the program should crash as this is an error that the program can't really treat. It could be caused either by the fact that it is not supported (and then it would error everytime the idle inhibit state was changed) or by a real error that happened for any reason, even though the method was supported.

So, as we can't really differentiate if the errors were caused by lack of support or some other error (at least not without some work) I believe it would be better to crash...

Also, in the case of a method not being supported, the program would probably not even reach this part, and would crash in the creation of the IdleInhibitor, in this case in https://github.com/rafaelrc7/wayland-pipewire-idle-inhibit/commit/de7e0fa759f50cbcc626c4a45dfbdb9b1722918e#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcR84-R88 . So I believe crashing when any IdleInhibitor fails is the right path.

**Comment by rafaelrc7** [comment]
@tjkirch I just implemented the dbus idle inhibitor. I saw in your original issue that you use NixOS, thus you can test it by running:
``
 nix run github:rafaelrc7/wayland-pipewire-idle-inhibit/feat/dbus -- -v INFO -d0 --no-wayland --dbus
``

It seems to be working. But I would recommend you testing it on your side, to be sure. Don´t forget to test your chosen media both with the program running and not. When running, idle should be inhibited, when not running, idle should happen. Please share any thought you have! Either related to the application running results and the code, as you've been reading the changes. Thanks!

I chose to implement dbus using `zbus` it seems to be more actively developed and has some nice features.

Furthermore, I also found the https://www.freedesktop.org/software/systemd/man/latest/org.freedesktop.login1.html dbus service, that also seems to be a option. Why the implemented one (ScreenSaver) is session related, this one interfaces directly to systemd-logind, I might also implement this as other option.

**Comment by tjkirch** [comment]
It works for me too.  Thank you!  I tested with `-bW` and it inhibits, and with `-n` or `-Bw` it does not, as expected.  `-bw` works fine too.  That means that creating the wayland v1 inhibitor does not panic on my machine, even though it doesn't function.  Does creating a dbus inhibitor panic on your non-Plasma machine?  If not, it seems like you could have them both enabled by default, to make things easier for most people, not having to think about arguments at all?

The code looks good to me.  I just had minor suggestions, if you're interested:
* (Unless you change defaults) In the READMDE, `-w` is marked as the default; you could also mark `-B` as a default, to make clear that D-Bus isn't enabled by default.
* When creating inhibitors in main.rs, and when calling inhibit/uninhibit in main.rs, there are panic calls on error - maybe include the type of inhibitor in the message, in case multiple are enabled?
* The `-n` argument conflicts with wayland; it could also conflict with dbus, for the same reason.  (I do see that `-b` conflicts with `-n`, but if wayland conflicts both ways, it's probably clearer to have dbus conflict both ways, too.)

**Comment by rafaelrc7** [comment]
> That means that creating the wayland v1 inhibitor does not panic on my machine

Yeah, Plasma does implement the idle-inhibit-unstable-v1 protocol, actually. It is mentioned in one of their changelogs (see my first comment in #1 ). It seems to be a bug on their part.

> Does creating a dbus inhibitor panic on your non-Plasma machine

It does not panic right away, on creation. However, when it tries to call the inhibit function, it does, with the following error:
``
org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files
``
This actually makes me wonder if I should call inhibit and uninhibit when creating the dbus inhibitor, so that it crashes right away if dbus is not supported.

However, I was able to test it using this project: https://github.com/bdwalton/inhibit-bridge that offers a daemon for this service. When running `inhibit-bridge`, the dbus idle inhibitor works fine as expected.

About your three suggestions, I agree with them all. But I believe a solution would be to just use one idle inhibitor at once, instead of allowing multiple concurrent ones... I would simplify the programs code, usage and error handling. I will push soon a new version with this change.

Thanks a lot for the input!

**Comment by rafaelrc7** [comment]
@tjkirch Hey, I just pushed what I believe is a good candidate to be merged to master. Basically I changed the code to use a single idle inhibitor backend at once, that can be setup either via cli args or the config file. I also improved some things such as the help menu, that now shows the options default values.

Pinging you to ask if you have any further critiques or comments. Thanks!

**Comment by tjkirch** [comment]
Still works great, thanks!  Just a couple small thoughts:
* Would it make sense to remove the `-b`, `-w`, and `-n` flags now that you have `-i` and only allow one?  That seems like it would simplify usage and simplify the code.  Maybe idle_inhibitor in settings/cli.rs wouldn't need to be an option, either, then, just an enum.  It looks like settings/mod.rs is already kind of that way, but maybe the rest of the code could match.
* It might be nice to accept "dbus" as well as "d-bus" as input in IdleInhibitor FromStr, since it's common to omit the hyphen.

**Comment by rafaelrc7** [comment]
> Would it make sense to remove the -b, -w, and -n flags now that you have -i and only allow one? That seems like it would simplify usage and simplify the code. Maybe idle_inhibitor in settings/cli.rs wouldn't need to be an option, either, then, just an enum. It looks like settings/mod.rs is already kind of that way, but maybe the rest of the code could match.

So, I kept those options to act as aliases, so that you could do just `-b` instead of `-i d-bus`. And, actually, it would not simplify the code that much, it would only remove the respective fields in the `settings/cli.rs::Args` struct. The `idle_inhibitor` field would still be an `Option`. If you notice, all the other fields of the `Args` struct that are not tagged with `#[serde(skip_serializing)]` are `Option`s. This is used to check when an user omits a argument so that a default value can be used. I know that the `clap` crate has a feature for that, but the issue is that I wanted to have an order of settings priority like so:  cli args > config file > defaults, and as the cli args are the last ones applied, having the defaults there would overwrite all settings set by the config file or defaults. So, the defaults are set in the `Settings` struct, and cli args that are omited are `None` and not serialised (`#[serde(skip_serializing_if = "::std::option::Option::is_none")]`), thus keeping the defaults unchanged (or the settings read from the config file).

> It might be nice to accept "dbus" as well as "d-bus" as input in IdleInhibitor FromStr, since it's common to omit the hyphen.

I like this suggestion and will apply it! I will push it soon. 

If you don't have any more suggestions, I guess I will open a PR, merge it and bump the release.

**Comment by tjkirch** [comment]
Sounds great!
