### ISSUE TITLE
Configuration question regardin player

### ISSUE THREAD

**Issue by letkan** [rafaelrc7/wayland-pipewire-idle-inhibit#6]
Hi, I'm on Labwc and wayland-pipewire-idle-inhibit gets enabled while playing videos in Firefox (Netflix, youtube, etc.) but if I stop the player but don't close the tab with the player, the inhibitor never disables and the screen stays on. Is there any way to stop the inhibitor without quitting the player, just by stopping it?

**Comment by rafaelrc7** [comment]
Thats weird, it works fine for me. Pausing the video (be it on youtube or netflix) in Firefox keeps the pipewire link alive, but it is deactivated, what is enough for the program to resume idling. Could you post some of the logs with the TRACE level? Specially of the moment when you play the video and pause it.

**Comment by letkan** [comment]
[trace.txt](https://github.com/rafaelrc7/wayland-pipewire-idle-inhibit/files/14982974/trace.txt)
The inhibitor is ENABLED even before I start playing a youtube video. After stopping the video, no output, I was expecting DISABLED. This is on Arch linux with Labwc. I'm also using sfwbar which has an inhibitor module but it's manual and it works as expected, on and off.

**Comment by rafaelrc7** [comment]
> The inhibitor is ENABLED even before I start playing a youtube video. 

I see, this may point to another program keeping the idle inhibited. I believe a good way to diagnose it is to export the whole log, could you send it?

**Comment by letkan** [comment]
You mean, start logging, launch firefox, go to youtube, start a video?

**Comment by letkan** [comment]
Restarted computer, started `wayland-pipewire-idle-inhibit -v TRACE`, launched Firefox, go to youtube, start video, stop video, quit Firefox. 
[trace-2.txt](https://github.com/rafaelrc7/wayland-pipewire-idle-inhibit/files/14983461/trace-2.txt)

**Comment by rafaelrc7** [comment]
In this logs it seems to be working fine. It got enabled around line 588 and disabled around line 700. The log says it was enabled 5 seconds after Firefox started playing something and it got disabled when the Firefox link was removed.

I believe Firefox is *not* the problem. Probably some other app in your computer is causing the idle to be inhibited. You should generate the logs if you are able to reproduce the problem (idle not being resumed after firefox is paused), trying to reopen all software that was open before. 

Another good tool to debug it is [Helvum](https://gitlab.freedesktop.org/pipewire/helvum) (it is also available in either Arch's official repos or AUR), it is a nice program that renders the PipeWire graph. You should look for filled lines between apps and your sink, those are the links that inhibit idle. Dotted lines are deactivated links, that happens for example when you pause a video, and they do not inhibit idle, you must look for the filled lines.

**Comment by letkan** [comment]
Aha, thanks for looking into it, I'll keep digging.

**Comment by rafaelrc7** [comment]
If you do find the cause, please report it here, at least for future reference. And if it applies, you could add it to the node blacklist (as described in the README). The name you put in the blacklist is the same name as Helvum uses for the nodes.

**Comment by letkan** [comment]
Here's Helvum. Honestly, I know nothing about audio stuff but the picture looks straight forward to me..
![20240415_22h58m50s_grim](https://github.com/rafaelrc7/wayland-pipewire-idle-inhibit/assets/9017461/bb2af579-c382-4113-92ab-edabc2269f56)

**Comment by rafaelrc7** [comment]
Yeah, that active link would keep idling inhibited. Does it stay like that when you pause the video?

**Comment by letkan** [comment]
It doesn't become dashed when pausing the video. That means an inhibitor is still running?

**Comment by rafaelrc7** [comment]
Yes it does. The "full" line represents a active link, that inhibits idle. A "dashed" line represents an inactive link, that *does not* inhibit idle. Normally, when pausing videos in firefox the link becomes inactive (represented by the dashed line). However, I am not sure why it is not working for you... 

Does your pipewire installation has anything special? Does your firefox has anything special? Just for testing, I would recommend you trying without any firefox extensions (may be on a private window).

**Comment by letkan** [comment]
You were absolutely right, I had an equalizer extension which caused the inhibitor to stay on. Without it it works as advertised :)
Thanks again for all the help

**Comment by rafaelrc7** [comment]
Ah, I see. Sadly, the program can't differentiate between silent and non-silent active links, just between active and non-active ones. Although that is something I would like to implement, if feasible, in the future. If it is not a deal breaker to you, you can disable the equalizer. I believe there are pipewire-native alternatives such as easyeffects.

**Comment by letkan** [comment]
I forgot about easyeffects, I played with it when it was still unstable, I'll check it out again.
